name: Docker Compose 
run-name: Docker Compose 🐳
on: [push]
jobs:
  Thest-The-Application:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application & Database 
        run: |
          docker compose -f compose.yaml up -d 
